version: 0.1
proxy:
  remoteurl: https://registry-1.docker.io
storage:
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  auth:
    htpasswd:
      realm: basic-realm
      path: /auth/htpasswd  # no such path, won't allow pushes
